server:
  port: 8080
  servlet:
    context-path: /api/v1/products

spring:
  application:
    name: products-service
  datasource:
    url: jdbc:postgresql://localhost:5432/productsdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true

management:
  server:
    base-path: /actuator
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always